config/routes.rb
Rails.application.routes.draw do
  resources :orders
  devise_for :users
  resources :provinces
  resources :pages
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories
  resources :products

  root to: "products#index"

  get "/p/:permalink", to: "pages#permalink", as: "permalink"

  get "search", to: "products#search", as: "search"

  get "cart", to: "products#cart", as: "cart"

  post "products/add_to_cart/:id", to: "products#add_to_cart", as: "add_to_cart"
  delete "products/remove_from_cart/:id", to: "products#remove_from_cart", as: "remove_from_cart"
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :users, dependent: :restrict_with_exception

  validates :name, :pst, :gst, :hst, presence: true
  validates :pst, :gst, :hst, numericality: true
end

app/controllers/provinces_controller.rb
class ProvincesController < InheritedResources::Base
  private

  def province_params
    params.require(:province).permit(:name, :pst, :gst, :hst)
  end
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/views/provinces/_form.html.erb
<%= form_with(model: province, local: true) do |form| %>
  <% if province.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(province.errors.count, "error") %> prohibited this province from being saved:</h2>

      <ul>
        <% province.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :pst %>
    <%= form.text_field :pst %>
  </div>

  <div class="field">
    <%= form.label :gst %>
    <%= form.text_field :gst %>
  </div>

  <div class="field">
    <%= form.label :hst %>
    <%= form.text_field :hst %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/provinces/edit.html.erb
<h1>Editing Province</h1>

<%= render 'form', province: @province %>

<%= link_to 'Show', @province %> |
<%= link_to 'Back', provinces_path %>

app/views/provinces/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Provinces</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Pst</th>
      <th>Gst</th>
      <th>Hst</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @provinces.each do |province| %>
      <tr>
        <td><%= province.name %></td>
        <td><%= province.pst %></td>
        <td><%= province.gst %></td>
        <td><%= province.hst %></td>
        <td><%= link_to 'Show', province %></td>
        <td><%= link_to 'Edit', edit_province_path(province) %></td>
        <td><%= link_to 'Destroy', province, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Province', new_province_path %>

app/views/provinces/new.html.erb
<h1>New Province</h1>

<%= render 'form', province: @province %>

<%= link_to 'Back', provinces_path %>

app/views/provinces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @province.name %>
</p>

<p>
  <strong>Pst:</strong>
  <%= @province.pst %>
</p>

<p>
  <strong>Gst:</strong>
  <%= @province.gst %>
</p>

<p>
  <strong>Hst:</strong>
  <%= @province.hst %>
</p>

<%= link_to 'Edit', edit_province_path(@province) %> |
<%= link_to 'Back', provinces_path %>