config/routes.rb
Rails.application.routes.draw do
  resources :orders
  devise_for :users
  resources :provinces
  resources :pages
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories
  resources :products

  root to: "products#index"

  get "/p/:permalink", to: "pages#permalink", as: "permalink"

  get "search", to: "products#search", as: "search"

  get "cart", to: "products#cart", as: "cart"

  post "products/add_to_cart/:id", to: "products#add_to_cart", as: "add_to_cart"
  delete "products/remove_from_cart/:id", to: "products#remove_from_cart", as: "remove_from_cart"
end

app/models/product.rb
class Product < ApplicationRecord
  has_and_belongs_to_many :categories
  accepts_nested_attributes_for :categories

  validate :one_or_more_categories?

  has_one_attached :image

  validates :name, :description, :price, presence: true
  validates :price, numericality: true

  def one_or_more_categories?
    errors.add(:cateories, "- need at least one category") if categories.empty?
  end

  def self.search(params)
    products = Product.joins(:categories_products).where(
      "products.name LIKE ? AND categories_products.category_id LIKE ?",
      "%#{params[:search_term]}%", "%#{params[:category]}%"
    )
    products
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]
  before_action :initialize_session
  before_action :load_cart

  # GET /products
  # GET /products.json
  def index
    @products = Product.all.page(params[:page]).per(5)
  end

  def search
    @products = Product.search(params)
  end

  def add_to_cart
    id = params[:id].to_i
    session[:cart] << id unless session[:cart].include?(id)
    redirect_to request.referer
  end

  def remove_from_cart
    id = params[:id].to_i
    session[:cart].delete(id)
    redirect_to request.referer
  end

  # GET /products/1
  # GET /products/1.json
  def show; end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit; end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:name, :description, :price, :image)
  end

  def initialize_session
    session[:cart] ||= []
  end

  def load_cart
    @cart = Product.find(session[:cart])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<li class="column is-one-fifth">
  <div class="card">
    <% if product.image.present? %>
      <div class="card-image">
        <figure class="image is-square">
          <%= image_tag product.image, alt: product.name %>
        </figure>
      </div>
    <% end %>
    <div class="card-content">
      <div class="media">
        <div class="media-content">
          <p class="title is-4"><%= link_to product.name, product %></p>
          <p class="subtitle is-6"><%= number_to_currency product.price %></p>
        </div>
      </div>

      <div class="content">
        <%= truncate(product.description, length: 200, separator: ' ') %>
      </div>
    </div>
  </div>
</li>

app/views/products/_search.html.erb
<%= form_with(url: search_path, local: true, method: "get") do %>
  <div class="field has-addons">
    <div class="control">
      <%= text_field_tag :search_term, nil, placeholder: 'search', class: 'input' %>
    </div>
    <div class="control">
      <div class ="select">
        <%= select_tag("category", options_for_select(Category.all.map{|el| [el.name, el.id]}.insert(0,"")), class: 'select') %>
      </div>
    </div>
    <div class="control">
      <%= submit_tag("Search", class: 'button is-info') %>
    </div>
  </div>
<% end %>

app/views/products/cart.html.erb
<div class="container">
  <h1 class="subtitle is-1">Cart</h1>
  <% if @cart.count > 0 %>
    <table class="table">
      <% @cart.each do |product| %>
        <tr>
          <th><%= product.name %></th>
          <th>$<%= product.price %></th>
          <th><%= link_to 'remove', remove_from_cart_path(product), method: :delete %></th>
        </tr>
      <% end %>
    </table>
    <% if user_signed_in? %>
      <%= button_to 'Checkout', new_order_path, method: :get, :class => 'button' %>
    <% else %>
      <p>Please sign in to continue</p>
    <% end %>
  <% else %>
    <p class="subtitle is-5">Your cart is empty</p>
  <% end %>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1 class="subtitle is-1">Products</h1>
  <%= paginate @products %>
  <ul class="columns is-multiline">
    <% @products.each do |product| %>
      <%= render partial: 'product', object: product %>
    <% end %>
  </ul>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/search.html.erb
<div class="container">
  <ul class="columns is-multiline">
    <%= render partial: 'products/product', collection: @products %>
  </ul>
</div>

app/views/products/show.html.erb
<div class="container">
  <h1 class="subtitle is-1">Details</h1>
  <div class="column is-one-third">
    <div class="card">
      <% if @product.image.present? %>
        <div class="card-image">
          <figure class="image is-square">
            <%= image_tag @product.image %>
          </figure>
        </div>
      <% end %>
      <div class="card-content">
        <div class="media">
          <div class="media-content">
            <p class="title is-4"><%= @product.name %></p>
            <p class="subtitle is-6">$<%= @product.price %></p>
          </div>
        </div>

        <div class="content">
          <p><%= @product.description %></p>
          <% if @cart.include?(@product) %>
            <p>Product in cart.</p>
          <% else %>
            <p><%= link_to 'Add to cart', add_to_cart_path(@product.id), method: :post %></p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>